FROM registry.redhat.io/rhel8/dotnet-50

USER 0

COPY ContosoTeamStats/bin /opt/app-root/app
RUN chown -R 1001:0 /opt/app-root/app

USER 1001
CMD dotnet /opt/app-root/app/Release/net5.0/ContosoTeamStats.dll
