apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

images:
- name: quay.io/kskels/aspnet-core-app
  newTag: quay.io/kskels/aspnet-core-app:v1.0
namespace: dotnet-gitops-prod


