apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aspnet-core-app
  name: aspnet-core-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnet-core-app
  template:
    metadata:
      labels:
        app: aspnet-core-app
    spec:
      containers:
        - image: quay.io/kskels/aspnet-core-app:v1.0
          imagePullPolicy: Always
          name: aspnet-core-app
          ports:
            - containerPort: 8080
              protocol: TCP

          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
