resources:
- dotnet-cicd-ns.yaml
- rolebindings/argocd-admin.yaml

- tasks/task-apply-manifests.yaml
- tasks/task-deploy-to-prod.yaml
- tasks/task-dotnet-build-and-publish.yaml
- tasks/task-dotnet-build.yaml
- tasks/task-get-archive.yaml
- tasks/task-update-deployment.yaml

- triggers/event-listener-route.yaml
- triggers/event-listener.yaml
- triggers/trigger-binding.yaml
- triggers/trigger-template.yaml
- triggers/trigger.yaml
