apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dotnet-build
spec:
  workspaces:
    - name: source
  params:
    - name: source_dir
      description: Location of image to be patched with
      type: string
      default: "."
  steps:
    - name: publish
      image: registry.redhat.io/ubi8/dotnet-50
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          cd $(inputs.params.source_dir)
          dotnet publish -c Release
